name = "erc721"
description = "Official Cannon build for @openzeppelin/contracts/token/ERC721/ERC721.sol contract"
tags = ["ERC721", "Token"]

[setting.salt]
defaultValue = "ERC721"

[setting.name]
defaultValue = "Token"

[setting.symbol]
defaultValue = "TKN"

[contract.erc721]
artifact = "ERC721"
args = ["<%= settings.name %>", "<%= settings.symbol %>"]
salt = "<%= settings.salt %>"
step = 1
