name = "erc20"
description = "Official Cannon build for @openzeppelin/contracts/token/ERC20/ERC20.sol contract"
tags = ["ERC20", "Token"]

[setting.salt]
defaultValue = "ERC20"

[setting.name]
defaultValue = "Token"

[setting.symbol]
defaultValue = "TKN"

[contract.erc20]
artifact = "ERC20"
args = ["<%= settings.name %>", "<%= settings.symbol %>"]
salt = "<%= settings.salt %>"
step = 1
